# Site settings
name: BLOG
email: 1009842987@qq.com
author: Nacl
url: http://github.com/shiyan-NaCl
github: https://github.com/shiyan-NaCl
baseurl: "/BLOG"
description: Write blogs!
meta_description: BLOGS BLOGS
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: shiyan-nacl

# Build settings
markdown: kramdown

